/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HsIcB3cuck5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Link } from "react-router-dom"

export function Hero() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-primary to-primary/80">
          <div className="container px-4 md:px-6 text-center text-primary-foreground">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl md:text-7xl">
                Elevate Your Skills, Dominate the Game
              </h1>
              <p className="max-w-[700px] mx-auto text-lg md:text-xl">
                Join the leaderboard and showcase your gaming prowess. Improve your skills, compete with friends, and
                become a true champion.
              </p>
              <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
                <Link
                  to="/game"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-primary-foreground px-8 text-sm font-medium text-primary shadow transition-colors hover:bg-secondary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                // prefetch={false}
                >
                  Start Playing
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <Card>
                <CardHeader>
                  <CardTitle>Top Plays</CardTitle>
                  <CardDescription>
                    Check out the latest high scores and see how you stack up against the competition.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Rank</TableHead>
                        <TableHead>Player</TableHead>
                        <TableHead>Score</TableHead>
                        <TableHead>Time</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>1</TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Avatar className="h-8 w-8">
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>JP</AvatarFallback>
                            </Avatar>
                            <span>Shadcn</span>
                          </div>
                        </TableCell>
                        <TableCell>12,345</TableCell>
                        <TableCell>1:23.45</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>2</TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Avatar className="h-8 w-8">
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>JD</AvatarFallback>
                            </Avatar>
                            <span>User2</span>
                          </div>
                        </TableCell>
                        <TableCell>11,987</TableCell>
                        <TableCell>1:25.78</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>3</TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Avatar className="h-8 w-8">
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>LM</AvatarFallback>
                            </Avatar>
                            <span>User3</span>
                          </div>
                        </TableCell>
                        <TableCell>10,654</TableCell>
                        <TableCell>1:30.12</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
              <div className="space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Unlock Your Potential</h2>
                  <p className="text-muted-foreground md:text-xl">
                    Dive into our immersive game and push your skills to the limit. Compete against players from around
                    the world and climb the leaderboard.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    to="/game"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  // prefetch={false}
                  >
                    Start Playing
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Memorize Quran Helper. All rights reserved.</p>
        {
          /*
                  <nav className="sm:ml-auto flex gap-4 sm:gap-6">
                    <a to="#" className="text-xs hover:underline underline-offset-4"
                    // prefetch={false}
                    >
                      Terms of Service
                    </a>
                    <a to="#" className="text-xs hover:underline underline-offset-4"
                    // prefetch={false}
                    >
                      Privacy
                    </a>
                  </nav>
           */
        }
      </footer>
    </div>
  )
}

